spring.datasource.url=jdbc:mysql://localhost:3306/personalDownloader

spring.datasource.username=root

spring.datasource.password=Dhairya123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
